### PR TITLE
remove index.d.ts

### PR DESCRIPTION
**Pull request by aalenliang**

### CODE REVIEW

**Comment by chrisgervang** [comment]
This is still an issue, right?

**Comment by NickCarton** [comment]
Hi, yes, I can confirm that I am still seeing this issue with the latest build of react-custom-scrollbars.

If I apply the changes in this PR, issues disappear.

**Comment by aalenliang** [comment]
The index.d.ts file is out of date, remove the index.d.ts in project, then typescript developers can use @types/react-custom-scrollbars which works well.

**Comment by ETNOL** [comment]
This is still an issue. Could this PR be merged?

**Comment by KhraksMamtsov** [comment]
Work fine with @types/react-custom-scrollbars.  @malte-wessel could you please accept this PR.

**Comment by malte-wessel** [comment]
Thank you!

**Pull request merged**
