### PR TITLE
RTL Integration

### PR DESCRIPTION
**Pull request by saeedrahimi**
set scrollbar position on left side with isRTL boolean properties

### CODE REVIEW

**Comment by joscha** [comment]
@malte-wessel any chance to get this reviewed and integrated?

**Comment by joscha** [comment]
Maybe a combination with #88?

**Comment by tomasfrancisco** [comment]
I would be so happy if this gets merged :)

**Comment by Shayan20** [comment]
Hey saeed rahimi autoHeight props not working properly in Rtl in your merge changes can you please resolve the issue I want to implement urgently in the project  thanks

**Pull request closed without merging**
