### PR TITLE
Update

### PR DESCRIPTION
**Pull request by danbrianwhite**
Update enables OSX, iOS, and Android OS to properly utilize custom scrollbars using native scrollable container for fast performance
-Removed getScrollbarWidth as it is no longer needed to resolve scrollbar sizing 
	(margin set to 100 which at this point is larger than any browser scrollbars)
-Removed unneeded mobile only tests because all tests now pass on mobile with custom scrollbars

Fixes for IE11 and other browsers to work better in various situations especially when a user mouse drag causes the scrollable div not to update the scrollbars and show the content out of sync

Updated and added tests based on changes to enable scrolling on OSX, iOS, and Android OS

Updated package.json npm scripts to run cross environment so the project can be built and tested directly on Windows

Added autoWidth, autoWidthMin, and autoWidthMax options for horizontal track so it is possible to avoid horizontal scrolling when desired.
-Updated readme with this info

### CODE REVIEW

**Comment by malte-wessel** [comment]
Cool, I'll have a look at it soon

**Comment by danbrianwhite** [comment]
@malte-wessel can you review the pull request and let me know if you plan on merging it? 

I would like to start using your main branch.

**Comment by malte-wessel** [comment]
@danbrianwhite thx for reminding me! I'm currently not planning to merge this, since this update comes with a lot of (breaking) changes and some general issues: (I just had a look at the code, didn't test it at all):

* why introduce another wrapper element?
* sometimes `100` is used,  sometimes `getPaddingWidth`, `getPaddingHeight`
* commented code lines

**Comment by danbrianwhite** [comment]
The update adds full support for custom scrollbars on mobile devices by adding a wrapper. The wrapper was added since mobile devices overlay scrollbars on the containing div. Since you cannot size the mobile scrollbars (ultimately 0 px) 100 px spacing was added to the wrapped element to accommodate for scrollbar sizes. All tests were updated to accommodate for not sizing the scrollbars and using a size of 100px. Additional tests were added for new functionality and all tests pass.

Pertaining to the 100px value, I'll refactor the comments and abstract out the exact px size in code and tests if you are interested in the PR updates. Let me know.

**Comment by tarwich** [comment]
Sorry for the **bump**...
Any update from @malte-wessel since the fixes from @danbrianwhite ?

**Comment by benwiley4000** [comment]
@danbrianwhite I'd like to see this stuff merged but it would probably be easier to get merged as multiple patches on separate branches. Can't speak for @malte-wessel but I know I find it frustrating dealing with patches that add a lot of different features/changes at once.

**Comment by malte-wessel** [comment]
yes, @benwiley4000 is right, it would be cool, to have the different features in separated PRs, so that we have a better overview of what has changed.

**Comment by danbrianwhite** [comment]
@malte-wessel @benwiley4000 - I'll split this out into features over the next week so some of the updates can be pulled in simply (like Windows build and test support).

**Comment by malte-wessel** [comment]
cool, thx @danbrianwhite for your effort!

**Comment by danbrianwhite** [comment]
@malte-wessel - I created 2 pull requests.

- Windows build and test (including sample) #109 
- Show scrollbars on all browsers (including Mac OS and iOS) @ #110 

I will create a pull request for the 3rd update, auto width, after we hash out and merge #110

**Comment by EmaSurianoFdv** [comment]
Hi guys, why is this pull request not accepted yet? 
Thanks!

**Comment by EduardJS** [comment]
I guess @malte-wessel is not around here anymore ?..

**Comment by tymochko** [comment]
Hi, @danbrianwhite, I just tried to switch to your version (from your fork) and it doesn't work as expected.
Scrollbars are always visible, even if content fits into container.

Windows 10 64 bit, latest Chrome

**Pull request closed without merging**
